#!/usr/bin/env bash
set -euo pipefail

step::cluster.chrony.collect.config::check() { return 1; }

step::cluster.chrony.collect.config::run() {
  local ctx="$1"
  shift
  local cluster_name="${KUBEXM_CLUSTER_NAME:-}"
  local arg
  for arg in "$@"; do
    case "${arg}" in
      --cluster=*) cluster_name="${arg#*=}" ;;
    esac
  done
  if [[ -z "${cluster_name}" ]]; then
    echo "missing required --cluster for create cluster" >&2
    return 2
  fi
  export KUBEXM_CLUSTER_NAME="${cluster_name}"

  : "${KUBEXM_ROOT:?KUBEXM_ROOT is required}"
  source "${KUBEXM_ROOT}/internal/context/context.sh"
  source "${KUBEXM_ROOT}/internal/logger/log.sh"
  source "${KUBEXM_ROOT}/internal/config/config.sh"
  source "${KUBEXM_ROOT}/internal/config/defaults.sh"
  source "${KUBEXM_ROOT}/internal/utils/identity.sh"

  local node_name
  node_name=$(identity::resolve_node_name)

  local ntp_servers
  ntp_servers=$(config::get "system.ntp_servers" "$(defaults::get_ntp_servers)")
  if [[ -z "${ntp_servers}" ]]; then
    ntp_servers=$(defaults::get_ntp_servers)
  fi

  local all_hosts
  all_hosts=$(config::get_all_host_names)
  if [[ -z "${all_hosts}" ]]; then
    log::error "No hosts found in host.yaml"
    return 1
  fi

  local local_ntp_servers=()
  local external_ntp_servers=()
  IFS=',' read -ra ntp_server_array <<< "${ntp_servers}"
  for server in "${ntp_server_array[@]}"; do
    server=$(echo "${server}" | xargs)
    if echo "${all_hosts}" | grep -qw "${server}"; then
      local_ntp_servers+=("${server}")
    else
      external_ntp_servers+=("${server}")
    fi
  done

  local role="client"
  for server_name in "${local_ntp_servers[@]}"; do
    if [[ "${node_name}" == "${server_name}" ]]; then
      role="server"
      break
    fi
  done

  local chrony_conf="# Chrony ${role^} Configuration - Generated by KubeXM\n"
  if [[ "${role}" == "server" ]]; then
    chrony_conf+="# This node acts as NTP server for the cluster\n\n"
    local upstream
    if [[ ${#external_ntp_servers[@]} -gt 0 ]]; then
      upstream="${external_ntp_servers[*]}"
    else
      upstream="ntp.aliyun.com time.cloudflare.com"
    fi
    for server in ${upstream}; do
      chrony_conf+="server ${server} iburst\n"
    done
    chrony_conf+="\n# Allow local network to sync\nallow 10.0.0.0/8\nallow 172.16.0.0/12\nallow 192.168.0.0/16\n\n# Serve time even if not synchronized\nlocal stratum 10\n\n# Record rate information\ndriftfile /var/lib/chrony/drift\n\n# Enable kernel RTC synchronization\nrtcsync\n\n# Log files\nlogdir /var/log/chrony\n"
  else
    chrony_conf+="# This node syncs time from cluster NTP servers\n\n"
    local client_servers=""
    if [[ ${#local_ntp_servers[@]} -gt 0 ]]; then
      local ips=()
      for server_name in "${local_ntp_servers[@]}"; do
        local server_ip
        server_ip=$(config::get_host_param "${server_name}" "address")
        [[ -n "${server_ip}" ]] && ips+=("${server_ip}")
      done
      client_servers="${ips[*]}"
    else
      if [[ ${#external_ntp_servers[@]} -gt 0 ]]; then
        client_servers="${external_ntp_servers[*]}"
      else
        client_servers="ntp.aliyun.com"
      fi
    fi
    for server in ${client_servers}; do
      chrony_conf+="server ${server} iburst prefer\n"
    done
    chrony_conf+="\n# Record rate information\ndriftfile /var/lib/chrony/drift\n\n# Enable kernel RTC synchronization\nrtcsync\n\n# Allow stepping clock on first sync\nmakestep 1.0 3\n\n# Log files\nlogdir /var/log/chrony\n"
  fi

  local chrony_dir conf_file
  chrony_dir="${KUBEXM_ROOT}/packages/${cluster_name}/${node_name}/chrony"
  mkdir -p "${chrony_dir}"
  conf_file="${chrony_dir}/chrony.conf"
  printf '%b' "${chrony_conf}" > "${conf_file}"

  context::set "chrony_node_name" "${node_name}"
  context::set "chrony_role" "${role}"
  context::set "chrony_conf_file" "${conf_file}"
}

step::cluster.chrony.collect.config::rollback() { return 0; }

step::cluster.chrony.collect.config::targets() {
  : "${KUBEXM_ROOT:?KUBEXM_ROOT is required}"
  source "${KUBEXM_ROOT}/internal/utils/targets.sh"
  targets::for_all_hosts
}
