apiVersion: kubexm.io/v1
kind: Host
metadata:
  name: test-22-kubeadm-3master-external-etcd
spec:
  hosts:
    - {name: master-01, address: 192.168.1.10, user: root}
    - {name: master-02, address: 192.168.1.11, user: root}
    - {name: master-03, address: 192.168.1.12, user: root}
  roleGroups:
    control-plane: [master-01, master-02, master-03]
