FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    apt-utils dpkg-dev apt-rdepends ca-certificates gnupg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
COPY containers/scripts/build-deb.sh /build-deb.sh
ENTRYPOINT ["/build-deb.sh"]
